import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { Roboto } from 'next/font/google';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';
import { Metadata } from 'next';
import ReactQueryProvider from '@/service/ReactQuery/index';
import Favicon from '../../public/favicon/favicon.png'
interface LayoutProps {
  children: React.ReactNode
}

export const metadata: Metadata = {
  icons: [
    {
      rel: 'icon',
      type: 'image/png',
      sizes: '32x32',
      url: Favicon.src,
    },
  ],
  title: "Pokemon App",
  description: "Generated by create next app",
}

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
});

export default function RootLayout({ children }: LayoutProps) {

  return (
    <html lang="en">
      <body className={roboto.variable} style={{ margin: 0 }}>
        <ReactQueryProvider>
          <AppRouterCacheProvider>
            <ThemeProvider theme={theme}>
              {children}
            </ThemeProvider>
          </AppRouterCacheProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}